# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_lego_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.BTN_SEL_COMPONENT = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_COMPONENT.setMinimumSize(QtCore.QSize(48, 0))
        self.BTN_SEL_COMPONENT.setMaximumSize(QtCore.QSize(48, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/network.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SEL_COMPONENT.setIcon(icon)
        self.BTN_SEL_COMPONENT.setCheckable(True)
        self.BTN_SEL_COMPONENT.setAutoExclusive(True)
        self.BTN_SEL_COMPONENT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_COMPONENT.setObjectName("BTN_SEL_COMPONENT")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_COMPONENT)
        self.BTN_SEL_COMPONENT_2 = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_COMPONENT_2.setMinimumSize(QtCore.QSize(48, 0))
        self.BTN_SEL_COMPONENT_2.setMaximumSize(QtCore.QSize(48, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/compartmentalise.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SEL_COMPONENT_2.setIcon(icon1)
        self.BTN_SEL_COMPONENT_2.setCheckable(True)
        self.BTN_SEL_COMPONENT_2.setAutoExclusive(True)
        self.BTN_SEL_COMPONENT_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_COMPONENT_2.setObjectName("BTN_SEL_COMPONENT_2")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_COMPONENT_2)
        self.BTN_SEL_SEQUENCE = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_SEQUENCE.setMinimumSize(QtCore.QSize(48, 0))
        self.BTN_SEL_SEQUENCE.setMaximumSize(QtCore.QSize(48, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sequence.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SEL_SEQUENCE.setIcon(icon2)
        self.BTN_SEL_SEQUENCE.setCheckable(True)
        self.BTN_SEL_SEQUENCE.setChecked(True)
        self.BTN_SEL_SEQUENCE.setAutoExclusive(True)
        self.BTN_SEL_SEQUENCE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_SEQUENCE.setObjectName("BTN_SEL_SEQUENCE")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_SEQUENCE)
        self.BTN_SEL_SUBSEQUENCE = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_SUBSEQUENCE.setMinimumSize(QtCore.QSize(48, 0))
        self.BTN_SEL_SUBSEQUENCE.setMaximumSize(QtCore.QSize(48, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/subsequence.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SEL_SUBSEQUENCE.setIcon(icon3)
        self.BTN_SEL_SUBSEQUENCE.setCheckable(True)
        self.BTN_SEL_SUBSEQUENCE.setAutoExclusive(True)
        self.BTN_SEL_SUBSEQUENCE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_SUBSEQUENCE.setObjectName("BTN_SEL_SUBSEQUENCE")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_SUBSEQUENCE)
        self.BTN_SEL_EDGE = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_EDGE.setMinimumSize(QtCore.QSize(48, 0))
        self.BTN_SEL_EDGE.setMaximumSize(QtCore.QSize(48, 16777215))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/edge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SEL_EDGE.setIcon(icon4)
        self.BTN_SEL_EDGE.setCheckable(True)
        self.BTN_SEL_EDGE.setAutoExclusive(True)
        self.BTN_SEL_EDGE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_EDGE.setObjectName("BTN_SEL_EDGE")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_EDGE)
        spacerItem = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.BTN_SEL_EDGE_2 = QtWidgets.QToolButton(self.frame)
        self.BTN_SEL_EDGE_2.setIcon(icon4)
        self.BTN_SEL_EDGE_2.setCheckable(True)
        self.BTN_SEL_EDGE_2.setAutoExclusive(True)
        self.BTN_SEL_EDGE_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SEL_EDGE_2.setObjectName("BTN_SEL_EDGE_2")
        self.horizontalLayout_23.addWidget(self.BTN_SEL_EDGE_2)
        spacerItem1 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.label_30 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_7.addWidget(self.pushButton_26)
        self.BTN_VIEW_SETTINGS = QtWidgets.QPushButton(Dialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW_SETTINGS.setIcon(icon5)
        self.BTN_VIEW_SETTINGS.setObjectName("BTN_VIEW_SETTINGS")
        self.horizontalLayout_7.addWidget(self.BTN_VIEW_SETTINGS)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.FRA_MAIN = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRA_MAIN.sizePolicy().hasHeightForWidth())
        self.FRA_MAIN.setSizePolicy(sizePolicy)
        self.FRA_MAIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FRA_MAIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRA_MAIN.setObjectName("FRA_MAIN")
        self.verticalLayout.addWidget(self.FRA_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BTN_SEL_COMPONENT.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to component edit mode.</p></body></html>"))
        self.BTN_SEL_COMPONENT.setText(_translate("Dialog", "NRFG"))
        self.BTN_SEL_COMPONENT_2.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to component edit mode.</p></body></html>"))
        self.BTN_SEL_COMPONENT_2.setText(_translate("Dialog", "Comp"))
        self.BTN_SEL_SEQUENCE.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to sequence edit mode.</p></body></html>"))
        self.BTN_SEL_SEQUENCE.setStatusTip(_translate("Dialog", "Remove sequence"))
        self.BTN_SEL_SEQUENCE.setText(_translate("Dialog", "Genes"))
        self.BTN_SEL_SUBSEQUENCE.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to subsequence edit mode.</p></body></html>"))
        self.BTN_SEL_SUBSEQUENCE.setStatusTip(_translate("Dialog", "Remove (merge) splits"))
        self.BTN_SEL_SUBSEQUENCE.setText(_translate("Dialog", "Dom"))
        self.BTN_SEL_EDGE.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_SEL_EDGE.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_SEL_EDGE.setText(_translate("Dialog", "Edge"))
        self.BTN_SEL_EDGE_2.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_SEL_EDGE_2.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_SEL_EDGE_2.setText(_translate("Dialog", "Change selection"))
        self.label_30.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_26.setText(_translate("Dialog", "Align"))


