# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_wizard_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1167, 894)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.LBL_HELP_TITLE = QtWidgets.QLabel(Dialog)
        self.LBL_HELP_TITLE.setObjectName("LBL_HELP_TITLE")
        self.verticalLayout.addWidget(self.LBL_HELP_TITLE)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.TXT_FILENAME = QtWidgets.QLineEdit(Dialog)
        self.TXT_FILENAME.setObjectName("TXT_FILENAME")
        self.horizontalLayout_20.addWidget(self.TXT_FILENAME)
        self.BTN_BROWSE_FILE = QtWidgets.QPushButton(Dialog)
        self.BTN_BROWSE_FILE.setObjectName("BTN_BROWSE_FILE")
        self.horizontalLayout_20.addWidget(self.BTN_BROWSE_FILE)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BTN_ADD_FILE = QtWidgets.QPushButton(Dialog)
        self.BTN_ADD_FILE.setObjectName("BTN_ADD_FILE")
        self.gridLayout_3.addWidget(self.BTN_ADD_FILE, 0, 1, 1, 1)
        self.BTN_REMOVE_FILE = QtWidgets.QPushButton(Dialog)
        self.BTN_REMOVE_FILE.setObjectName("BTN_REMOVE_FILE")
        self.gridLayout_3.addWidget(self.BTN_REMOVE_FILE, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.LST_FILES = QtWidgets.QTreeWidget(Dialog)
        self.LST_FILES.setObjectName("LST_FILES")
        self.LST_FILES.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.LST_FILES, 0, 0, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SPN_COMPONENT_TOLERANCE = QtWidgets.QSpinBox(Dialog)
        self.SPN_COMPONENT_TOLERANCE.setObjectName("SPN_COMPONENT_TOLERANCE")
        self.gridLayout_4.addWidget(self.SPN_COMPONENT_TOLERANCE, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 2, 0, 1, 1)
        self.CMB_ALIGNMENT_METHOD = QtWidgets.QComboBox(Dialog)
        self.CMB_ALIGNMENT_METHOD.setObjectName("CMB_ALIGNMENT_METHOD")
        self.gridLayout_4.addWidget(self.CMB_ALIGNMENT_METHOD, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.CMB_TREE_METHOD = QtWidgets.QComboBox(Dialog)
        self.CMB_TREE_METHOD.setObjectName("CMB_TREE_METHOD")
        self.gridLayout_4.addWidget(self.CMB_TREE_METHOD, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.BTN_OK = QtWidgets.QPushButton(Dialog)
        self.BTN_OK.setObjectName("BTN_OK")
        self.horizontalLayout.addWidget(self.BTN_OK)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "Groot Wizard"))
        self.label_9.setProperty("style", _translate("Dialog", "title"))
        self.LBL_HELP_TITLE.setText(_translate("Dialog", "The wizard performs the complete Groot workflow at once. If you\'d like to be guided through step-by-step, consider using the <a href=\"action:show_workflow\">workflow</a> instead."))
        self.LBL_HELP_TITLE.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_7.setText(_translate("Dialog", "Filename"))
        self.label_7.setProperty("style", _translate("Dialog", "heading"))
        self.label_10.setText(_translate("Dialog", "Specify the file where your output should be saved. You can open this file to view it in Groot after the wizard completes."))
        self.label_10.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_BROWSE_FILE.setText(_translate("Dialog", "Browse"))
        self.label_8.setText(_translate("Dialog", "Data"))
        self.label_8.setProperty("style", _translate("Dialog", "heading"))
        self.label_11.setText(_translate("Dialog", "Specify at least one FASTA file and its corresponding BLAST file."))
        self.label_11.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_ADD_FILE.setText(_translate("Dialog", "Add"))
        self.BTN_REMOVE_FILE.setText(_translate("Dialog", "Remove"))
        self.label_19.setText(_translate("Dialog", "Algorithms"))
        self.label_19.setProperty("style", _translate("Dialog", "heading"))
        self.label_13.setText(_translate("Dialog", "Setup the algorithms and choose your tools."))
        self.label_13.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_20.setText(_translate("Dialog", "Component tolerance"))
        self.label_22.setText(_translate("Dialog", "Tree method"))
        self.label_21.setText(_translate("Dialog", "Alignment method"))
        self.label_14.setText(_translate("Dialog", "When you\'re ready, click OK to run the wizard."))
        self.label_14.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_OK.setText(_translate("Dialog", "OK"))


