# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_lego_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(951, 859)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_23.setSpacing(8)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.BTN_CHANGE_SELECTION = QtWidgets.QPushButton(self.frame)
        self.BTN_CHANGE_SELECTION.setAutoDefault(False)
        self.BTN_CHANGE_SELECTION.setObjectName("BTN_CHANGE_SELECTION")
        self.horizontalLayout_23.addWidget(self.BTN_CHANGE_SELECTION)
        self.RAD_SEL_COMPONENT = QtWidgets.QRadioButton(self.frame)
        self.RAD_SEL_COMPONENT.setCheckable(True)
        self.RAD_SEL_COMPONENT.setAutoExclusive(True)
        self.RAD_SEL_COMPONENT.setObjectName("RAD_SEL_COMPONENT")
        self.horizontalLayout_23.addWidget(self.RAD_SEL_COMPONENT)
        self.RAD_SEL_GENES = QtWidgets.QRadioButton(self.frame)
        self.RAD_SEL_GENES.setCheckable(True)
        self.RAD_SEL_GENES.setChecked(True)
        self.RAD_SEL_GENES.setAutoExclusive(True)
        self.RAD_SEL_GENES.setObjectName("RAD_SEL_GENES")
        self.horizontalLayout_23.addWidget(self.RAD_SEL_GENES)
        self.RAD_SEL_DOMAINS = QtWidgets.QRadioButton(self.frame)
        self.RAD_SEL_DOMAINS.setCheckable(True)
        self.RAD_SEL_DOMAINS.setAutoExclusive(True)
        self.RAD_SEL_DOMAINS.setObjectName("RAD_SEL_DOMAINS")
        self.horizontalLayout_23.addWidget(self.RAD_SEL_DOMAINS)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.BTN_REFRESH = QtWidgets.QPushButton(self.frame)
        self.BTN_REFRESH.setAutoDefault(False)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_23.addWidget(self.BTN_REFRESH)
        self.BTN_ALIGN = QtWidgets.QPushButton(self.frame)
        self.BTN_ALIGN.setAutoDefault(False)
        self.BTN_ALIGN.setObjectName("BTN_ALIGN")
        self.horizontalLayout_23.addWidget(self.BTN_ALIGN)
        self.BTN_OPTIONS = QtWidgets.QPushButton(self.frame)
        self.BTN_OPTIONS.setAutoDefault(False)
        self.BTN_OPTIONS.setObjectName("BTN_OPTIONS")
        self.horizontalLayout_23.addWidget(self.BTN_OPTIONS)
        self.verticalLayout.addWidget(self.frame)
        self.LBL_NO_DOMAINS = QtWidgets.QLabel(Dialog)
        self.LBL_NO_DOMAINS.setObjectName("LBL_NO_DOMAINS")
        self.verticalLayout.addWidget(self.LBL_NO_DOMAINS)
        self.FRA_MAIN = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRA_MAIN.sizePolicy().hasHeightForWidth())
        self.FRA_MAIN.setSizePolicy(sizePolicy)
        self.FRA_MAIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FRA_MAIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRA_MAIN.setObjectName("FRA_MAIN")
        self.verticalLayout.addWidget(self.FRA_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BTN_CHANGE_SELECTION.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_CHANGE_SELECTION.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_CHANGE_SELECTION.setText(_translate("Dialog", "Select"))
        self.BTN_CHANGE_SELECTION.setProperty("style", _translate("Dialog", "dropdown"))
        self.RAD_SEL_COMPONENT.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to component edit mode.</p></body></html>"))
        self.RAD_SEL_COMPONENT.setText(_translate("Dialog", "Components"))
        self.RAD_SEL_GENES.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to sequence edit mode.</p></body></html>"))
        self.RAD_SEL_GENES.setStatusTip(_translate("Dialog", "Remove sequence"))
        self.RAD_SEL_GENES.setText(_translate("Dialog", "Genes"))
        self.RAD_SEL_DOMAINS.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to subsequence edit mode.</p></body></html>"))
        self.RAD_SEL_DOMAINS.setStatusTip(_translate("Dialog", "Remove (merge) splits"))
        self.RAD_SEL_DOMAINS.setText(_translate("Dialog", "Domains"))
        self.BTN_REFRESH.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_REFRESH.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.BTN_ALIGN.setText(_translate("Dialog", "Align"))
        self.BTN_ALIGN.setProperty("style", _translate("Dialog", "dropdown"))
        self.BTN_OPTIONS.setText(_translate("Dialog", "Options..."))
        self.LBL_NO_DOMAINS.setText(_translate("Dialog", "<html><head/><body><p>You have no domains defined, all genes will be shown as one domain. You need to <a href=\"action:show_domains\">generate domains</a> first.</p></body></html>"))
        self.LBL_NO_DOMAINS.setProperty("style", _translate("Dialog", "warning"))


