# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_workflow_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(512, 16777215))
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(4, -1, 4, 4)
        self.horizontalLayout_18.setSpacing(4)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.LBL_TITLE_MODEL = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_MODEL.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_MODEL.setSizePolicy(sizePolicy)
        self.LBL_TITLE_MODEL.setObjectName("LBL_TITLE_MODEL")
        self.horizontalLayout_18.addWidget(self.LBL_TITLE_MODEL)
        self.LBL_INFO_MODEL = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_MODEL.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_MODEL.setSizePolicy(sizePolicy)
        self.LBL_INFO_MODEL.setStyleSheet("color:red;")
        self.LBL_INFO_MODEL.setObjectName("LBL_INFO_MODEL")
        self.horizontalLayout_18.addWidget(self.LBL_INFO_MODEL)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BTN_MODEL_NEW = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_MODEL_NEW.sizePolicy().hasHeightForWidth())
        self.BTN_MODEL_NEW.setSizePolicy(sizePolicy)
        self.BTN_MODEL_NEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_MODEL_NEW.setObjectName("BTN_MODEL_NEW")
        self.horizontalLayout_5.addWidget(self.BTN_MODEL_NEW)
        self.BTN_MODEL_LOAD = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_MODEL_LOAD.sizePolicy().hasHeightForWidth())
        self.BTN_MODEL_LOAD.setSizePolicy(sizePolicy)
        self.BTN_MODEL_LOAD.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_MODEL_LOAD.setObjectName("BTN_MODEL_LOAD")
        self.horizontalLayout_5.addWidget(self.BTN_MODEL_LOAD)
        self.BTN_MODEL_SAVE = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_MODEL_SAVE.sizePolicy().hasHeightForWidth())
        self.BTN_MODEL_SAVE.setSizePolicy(sizePolicy)
        self.BTN_MODEL_SAVE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_MODEL_SAVE.setObjectName("BTN_MODEL_SAVE")
        self.horizontalLayout_5.addWidget(self.BTN_MODEL_SAVE)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(4, -1, 4, 4)
        self.horizontalLayout_17.setSpacing(4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.LBL_TITLE_DATA = QtWidgets.QLabel(self.verticalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_DATA.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_DATA.setSizePolicy(sizePolicy)
        self.LBL_TITLE_DATA.setObjectName("LBL_TITLE_DATA")
        self.horizontalLayout_17.addWidget(self.LBL_TITLE_DATA)
        self.LBL_INFO_DATA = QtWidgets.QLabel(self.verticalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_DATA.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_DATA.setSizePolicy(sizePolicy)
        self.LBL_INFO_DATA.setStyleSheet("color:red;")
        self.LBL_INFO_DATA.setObjectName("LBL_INFO_DATA")
        self.horizontalLayout_17.addWidget(self.LBL_INFO_DATA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout_19.setSpacing(4)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.BTN_DATA_IMPORT = QtWidgets.QPushButton(self.verticalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_DATA_IMPORT.sizePolicy().hasHeightForWidth())
        self.BTN_DATA_IMPORT.setSizePolicy(sizePolicy)
        self.BTN_DATA_IMPORT.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_DATA_IMPORT.setObjectName("BTN_DATA_IMPORT")
        self.horizontalLayout_19.addWidget(self.BTN_DATA_IMPORT)
        self.BTN_DATA_VIEW = QtWidgets.QPushButton(self.verticalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_DATA_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_DATA_VIEW.setSizePolicy(sizePolicy)
        self.BTN_DATA_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_DATA_VIEW.setObjectName("BTN_DATA_VIEW")
        self.horizontalLayout_19.addWidget(self.BTN_DATA_VIEW)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.verticalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalFrame_3 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_16.setSpacing(4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.LBL_TITLE_COMPONENTS = QtWidgets.QLabel(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_COMPONENTS.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_COMPONENTS.setSizePolicy(sizePolicy)
        self.LBL_TITLE_COMPONENTS.setObjectName("LBL_TITLE_COMPONENTS")
        self.horizontalLayout_16.addWidget(self.LBL_TITLE_COMPONENTS)
        self.LBL_INFO_COMPONENTS = QtWidgets.QLabel(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_COMPONENTS.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_COMPONENTS.setSizePolicy(sizePolicy)
        self.LBL_INFO_COMPONENTS.setStyleSheet("color:red;")
        self.LBL_INFO_COMPONENTS.setObjectName("LBL_INFO_COMPONENTS")
        self.horizontalLayout_16.addWidget(self.LBL_INFO_COMPONENTS)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BTN_COMPONENTS_CREATE = QtWidgets.QPushButton(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_COMPONENTS_CREATE.sizePolicy().hasHeightForWidth())
        self.BTN_COMPONENTS_CREATE.setSizePolicy(sizePolicy)
        self.BTN_COMPONENTS_CREATE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_COMPONENTS_CREATE.setObjectName("BTN_COMPONENTS_CREATE")
        self.horizontalLayout_9.addWidget(self.BTN_COMPONENTS_CREATE)
        self.BTN_COMPONENTS_DELETE = QtWidgets.QPushButton(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_COMPONENTS_DELETE.sizePolicy().hasHeightForWidth())
        self.BTN_COMPONENTS_DELETE.setSizePolicy(sizePolicy)
        self.BTN_COMPONENTS_DELETE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_COMPONENTS_DELETE.setObjectName("BTN_COMPONENTS_DELETE")
        self.horizontalLayout_9.addWidget(self.BTN_COMPONENTS_DELETE)
        self.BTN_COMPONENTS_VIEW = QtWidgets.QPushButton(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_COMPONENTS_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_COMPONENTS_VIEW.setSizePolicy(sizePolicy)
        self.BTN_COMPONENTS_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_COMPONENTS_VIEW.setObjectName("BTN_COMPONENTS_VIEW")
        self.horizontalLayout_9.addWidget(self.BTN_COMPONENTS_VIEW)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addWidget(self.verticalFrame_3)
        self.verticalFrame_4 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.LBL_TITLE_ALIGNMENT = QtWidgets.QLabel(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_ALIGNMENT.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_ALIGNMENT.setSizePolicy(sizePolicy)
        self.LBL_TITLE_ALIGNMENT.setObjectName("LBL_TITLE_ALIGNMENT")
        self.horizontalLayout_15.addWidget(self.LBL_TITLE_ALIGNMENT)
        self.LBL_INFO_ALIGN = QtWidgets.QLabel(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_ALIGN.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_ALIGN.setSizePolicy(sizePolicy)
        self.LBL_INFO_ALIGN.setStyleSheet("color:red;")
        self.LBL_INFO_ALIGN.setObjectName("LBL_INFO_ALIGN")
        self.horizontalLayout_15.addWidget(self.LBL_INFO_ALIGN)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BTN_ALIGNMENT_CREATE = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ALIGNMENT_CREATE.sizePolicy().hasHeightForWidth())
        self.BTN_ALIGNMENT_CREATE.setSizePolicy(sizePolicy)
        self.BTN_ALIGNMENT_CREATE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_ALIGNMENT_CREATE.setObjectName("BTN_ALIGNMENT_CREATE")
        self.horizontalLayout_11.addWidget(self.BTN_ALIGNMENT_CREATE)
        self.BTN_ALIGNMENT_DELETE = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ALIGNMENT_DELETE.sizePolicy().hasHeightForWidth())
        self.BTN_ALIGNMENT_DELETE.setSizePolicy(sizePolicy)
        self.BTN_ALIGNMENT_DELETE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_ALIGNMENT_DELETE.setObjectName("BTN_ALIGNMENT_DELETE")
        self.horizontalLayout_11.addWidget(self.BTN_ALIGNMENT_DELETE)
        self.BTN_ALIGNMENT_VIEW = QtWidgets.QPushButton(self.verticalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ALIGNMENT_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_ALIGNMENT_VIEW.setSizePolicy(sizePolicy)
        self.BTN_ALIGNMENT_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_ALIGNMENT_VIEW.setObjectName("BTN_ALIGNMENT_VIEW")
        self.horizontalLayout_11.addWidget(self.BTN_ALIGNMENT_VIEW)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addWidget(self.verticalFrame_4)
        self.verticalFrame_6 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_14.setSpacing(4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.LBL_TITLE_TREES = QtWidgets.QLabel(self.verticalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_TREES.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_TREES.setSizePolicy(sizePolicy)
        self.LBL_TITLE_TREES.setObjectName("LBL_TITLE_TREES")
        self.horizontalLayout_14.addWidget(self.LBL_TITLE_TREES)
        self.LBL_INFO_TREES = QtWidgets.QLabel(self.verticalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_TREES.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_TREES.setSizePolicy(sizePolicy)
        self.LBL_INFO_TREES.setStyleSheet("color:red;")
        self.LBL_INFO_TREES.setObjectName("LBL_INFO_TREES")
        self.horizontalLayout_14.addWidget(self.LBL_INFO_TREES)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.BTN_TREES_CREATE = QtWidgets.QPushButton(self.verticalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TREES_CREATE.sizePolicy().hasHeightForWidth())
        self.BTN_TREES_CREATE.setSizePolicy(sizePolicy)
        self.BTN_TREES_CREATE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_TREES_CREATE.setObjectName("BTN_TREES_CREATE")
        self.horizontalLayout_10.addWidget(self.BTN_TREES_CREATE)
        self.BTN_TREES_DELETE = QtWidgets.QPushButton(self.verticalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TREES_DELETE.sizePolicy().hasHeightForWidth())
        self.BTN_TREES_DELETE.setSizePolicy(sizePolicy)
        self.BTN_TREES_DELETE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_TREES_DELETE.setObjectName("BTN_TREES_DELETE")
        self.horizontalLayout_10.addWidget(self.BTN_TREES_DELETE)
        self.BTN_TREES_VIEW = QtWidgets.QPushButton(self.verticalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TREES_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_TREES_VIEW.setSizePolicy(sizePolicy)
        self.BTN_TREES_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_TREES_VIEW.setObjectName("BTN_TREES_VIEW")
        self.horizontalLayout_10.addWidget(self.BTN_TREES_VIEW)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.verticalFrame_6)
        self.verticalFrame_5 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LBL_TITLE_FUSIONS = QtWidgets.QLabel(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_FUSIONS.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_FUSIONS.setSizePolicy(sizePolicy)
        self.LBL_TITLE_FUSIONS.setObjectName("LBL_TITLE_FUSIONS")
        self.horizontalLayout_8.addWidget(self.LBL_TITLE_FUSIONS)
        self.LBL_INFO_FUSIONS = QtWidgets.QLabel(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_FUSIONS.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_FUSIONS.setSizePolicy(sizePolicy)
        self.LBL_INFO_FUSIONS.setStyleSheet("color:red;")
        self.LBL_INFO_FUSIONS.setObjectName("LBL_INFO_FUSIONS")
        self.horizontalLayout_8.addWidget(self.LBL_INFO_FUSIONS)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.BTN_FUSIONS_CREATE = QtWidgets.QPushButton(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_FUSIONS_CREATE.sizePolicy().hasHeightForWidth())
        self.BTN_FUSIONS_CREATE.setSizePolicy(sizePolicy)
        self.BTN_FUSIONS_CREATE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_FUSIONS_CREATE.setObjectName("BTN_FUSIONS_CREATE")
        self.horizontalLayout_12.addWidget(self.BTN_FUSIONS_CREATE)
        self.BTN_FUSIONS_DELETE = QtWidgets.QPushButton(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_FUSIONS_DELETE.sizePolicy().hasHeightForWidth())
        self.BTN_FUSIONS_DELETE.setSizePolicy(sizePolicy)
        self.BTN_FUSIONS_DELETE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_FUSIONS_DELETE.setObjectName("BTN_FUSIONS_DELETE")
        self.horizontalLayout_12.addWidget(self.BTN_FUSIONS_DELETE)
        self.BTN_FUSIONS_VIEW = QtWidgets.QPushButton(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_FUSIONS_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_FUSIONS_VIEW.setSizePolicy(sizePolicy)
        self.BTN_FUSIONS_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_FUSIONS_VIEW.setObjectName("BTN_FUSIONS_VIEW")
        self.horizontalLayout_12.addWidget(self.BTN_FUSIONS_VIEW)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addWidget(self.verticalFrame_5)
        self.verticalFrame_7 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LBL_TITLE_NRFG = QtWidgets.QLabel(self.verticalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_TITLE_NRFG.sizePolicy().hasHeightForWidth())
        self.LBL_TITLE_NRFG.setSizePolicy(sizePolicy)
        self.LBL_TITLE_NRFG.setObjectName("LBL_TITLE_NRFG")
        self.horizontalLayout_6.addWidget(self.LBL_TITLE_NRFG)
        self.LBL_INFO_NRFG = QtWidgets.QLabel(self.verticalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_INFO_NRFG.sizePolicy().hasHeightForWidth())
        self.LBL_INFO_NRFG.setSizePolicy(sizePolicy)
        self.LBL_INFO_NRFG.setStyleSheet("color:red;")
        self.LBL_INFO_NRFG.setObjectName("LBL_INFO_NRFG")
        self.horizontalLayout_6.addWidget(self.LBL_INFO_NRFG)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.BTN_NRFG_CREATE = QtWidgets.QPushButton(self.verticalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_NRFG_CREATE.sizePolicy().hasHeightForWidth())
        self.BTN_NRFG_CREATE.setSizePolicy(sizePolicy)
        self.BTN_NRFG_CREATE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_NRFG_CREATE.setObjectName("BTN_NRFG_CREATE")
        self.horizontalLayout_13.addWidget(self.BTN_NRFG_CREATE)
        self.BTN_NRFG_DELETE = QtWidgets.QPushButton(self.verticalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_NRFG_DELETE.sizePolicy().hasHeightForWidth())
        self.BTN_NRFG_DELETE.setSizePolicy(sizePolicy)
        self.BTN_NRFG_DELETE.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_NRFG_DELETE.setObjectName("BTN_NRFG_DELETE")
        self.horizontalLayout_13.addWidget(self.BTN_NRFG_DELETE)
        self.BTN_NRFG_VIEW = QtWidgets.QPushButton(self.verticalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_NRFG_VIEW.sizePolicy().hasHeightForWidth())
        self.BTN_NRFG_VIEW.setSizePolicy(sizePolicy)
        self.BTN_NRFG_VIEW.setMaximumSize(QtCore.QSize(16777215, 32))
        self.BTN_NRFG_VIEW.setObjectName("BTN_NRFG_VIEW")
        self.horizontalLayout_13.addWidget(self.BTN_NRFG_VIEW)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addWidget(self.verticalFrame_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LBL_TITLE_MODEL.setText(_translate("Dialog", "1. Model"))
        self.LBL_TITLE_MODEL.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_MODEL.setText(_translate("Dialog", "<"))
        self.LBL_INFO_MODEL.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_MODEL_NEW.setText(_translate("Dialog", "New"))
        self.BTN_MODEL_LOAD.setText(_translate("Dialog", "Load"))
        self.BTN_MODEL_SAVE.setText(_translate("Dialog", "Save"))
        self.LBL_TITLE_DATA.setText(_translate("Dialog", "2. Data"))
        self.LBL_TITLE_DATA.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_DATA.setText(_translate("Dialog", "<"))
        self.LBL_INFO_DATA.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_DATA_IMPORT.setText(_translate("Dialog", "Import"))
        self.BTN_DATA_VIEW.setText(_translate("Dialog", "View"))
        self.LBL_TITLE_COMPONENTS.setText(_translate("Dialog", "3. Components"))
        self.LBL_TITLE_COMPONENTS.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_COMPONENTS.setText(_translate("Dialog", "<"))
        self.LBL_INFO_COMPONENTS.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_COMPONENTS_CREATE.setText(_translate("Dialog", "Generate"))
        self.BTN_COMPONENTS_DELETE.setText(_translate("Dialog", "Delete"))
        self.BTN_COMPONENTS_VIEW.setText(_translate("Dialog", "View"))
        self.LBL_TITLE_ALIGNMENT.setText(_translate("Dialog", "4. Alignment"))
        self.LBL_TITLE_ALIGNMENT.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_ALIGN.setText(_translate("Dialog", "<"))
        self.LBL_INFO_ALIGN.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_ALIGNMENT_CREATE.setText(_translate("Dialog", "Generate"))
        self.BTN_ALIGNMENT_DELETE.setText(_translate("Dialog", "Delete"))
        self.BTN_ALIGNMENT_VIEW.setText(_translate("Dialog", "View"))
        self.LBL_TITLE_TREES.setText(_translate("Dialog", "5. Trees"))
        self.LBL_TITLE_TREES.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_TREES.setText(_translate("Dialog", "<"))
        self.LBL_INFO_TREES.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_TREES_CREATE.setText(_translate("Dialog", "Generate"))
        self.BTN_TREES_DELETE.setText(_translate("Dialog", "Delete"))
        self.BTN_TREES_VIEW.setText(_translate("Dialog", "View"))
        self.LBL_TITLE_FUSIONS.setText(_translate("Dialog", "6. Fusions"))
        self.LBL_TITLE_FUSIONS.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_FUSIONS.setText(_translate("Dialog", "<"))
        self.LBL_INFO_FUSIONS.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_FUSIONS_CREATE.setText(_translate("Dialog", "Generate"))
        self.BTN_FUSIONS_DELETE.setText(_translate("Dialog", "Delete"))
        self.BTN_FUSIONS_VIEW.setText(_translate("Dialog", "View"))
        self.LBL_TITLE_NRFG.setText(_translate("Dialog", "7. NRFG"))
        self.LBL_TITLE_NRFG.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_INFO_NRFG.setText(_translate("Dialog", "<"))
        self.LBL_INFO_NRFG.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_NRFG_CREATE.setText(_translate("Dialog", "Generate"))
        self.BTN_NRFG_DELETE.setText(_translate("Dialog", "Delete"))
        self.BTN_NRFG_VIEW.setText(_translate("Dialog", "View"))

