# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_workflow_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 632)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 19, 0, 1, 2)
        self.LBL_NRFG = QtWidgets.QLabel(Dialog)
        self.LBL_NRFG.setObjectName("LBL_NRFG")
        self.gridLayout.addWidget(self.LBL_NRFG, 16, 0, 1, 1)
        self.LBL_FUSIONS = QtWidgets.QLabel(Dialog)
        self.LBL_FUSIONS.setObjectName("LBL_FUSIONS")
        self.gridLayout.addWidget(self.LBL_FUSIONS, 14, 0, 1, 1)
        self.LBL_ALIGNMENTS = QtWidgets.QLabel(Dialog)
        self.LBL_ALIGNMENTS.setObjectName("LBL_ALIGNMENTS")
        self.gridLayout.addWidget(self.LBL_ALIGNMENTS, 10, 0, 1, 1)
        self.TXT_TREES = QtWidgets.QLineEdit(Dialog)
        self.TXT_TREES.setReadOnly(True)
        self.TXT_TREES.setObjectName("TXT_TREES")
        self.gridLayout.addWidget(self.TXT_TREES, 12, 1, 1, 1)
        self.LBL_TREES = QtWidgets.QLabel(Dialog)
        self.LBL_TREES.setObjectName("LBL_TREES")
        self.gridLayout.addWidget(self.LBL_TREES, 12, 0, 1, 1)
        self.LBL_SEQUENCES = QtWidgets.QLabel(Dialog)
        self.LBL_SEQUENCES.setObjectName("LBL_SEQUENCES")
        self.gridLayout.addWidget(self.LBL_SEQUENCES, 3, 0, 1, 1)
        self.TXT_SEQUENCES = QtWidgets.QLineEdit(Dialog)
        self.TXT_SEQUENCES.setReadOnly(True)
        self.TXT_SEQUENCES.setObjectName("TXT_SEQUENCES")
        self.gridLayout.addWidget(self.TXT_SEQUENCES, 3, 1, 1, 1)
        self.TXT_COMPONENTS = QtWidgets.QLineEdit(Dialog)
        self.TXT_COMPONENTS.setReadOnly(True)
        self.TXT_COMPONENTS.setObjectName("TXT_COMPONENTS")
        self.gridLayout.addWidget(self.TXT_COMPONENTS, 6, 1, 1, 1)
        self.LBL_COMPONENTS = QtWidgets.QLabel(Dialog)
        self.LBL_COMPONENTS.setObjectName("LBL_COMPONENTS")
        self.gridLayout.addWidget(self.LBL_COMPONENTS, 6, 0, 1, 1)
        self.TXT_ALIGNMENTS = QtWidgets.QLineEdit(Dialog)
        self.TXT_ALIGNMENTS.setReadOnly(True)
        self.TXT_ALIGNMENTS.setObjectName("TXT_ALIGNMENTS")
        self.gridLayout.addWidget(self.TXT_ALIGNMENTS, 10, 1, 1, 1)
        self.TXT_NRFG = QtWidgets.QLineEdit(Dialog)
        self.TXT_NRFG.setReadOnly(True)
        self.TXT_NRFG.setObjectName("TXT_NRFG")
        self.gridLayout.addWidget(self.TXT_NRFG, 16, 1, 1, 1)
        self.TXT_FUSIONS = QtWidgets.QLineEdit(Dialog)
        self.TXT_FUSIONS.setReadOnly(True)
        self.TXT_FUSIONS.setObjectName("TXT_FUSIONS")
        self.gridLayout.addWidget(self.TXT_FUSIONS, 14, 1, 1, 1)
        self.LBL_DOMAINS = QtWidgets.QLabel(Dialog)
        self.LBL_DOMAINS.setObjectName("LBL_DOMAINS")
        self.gridLayout.addWidget(self.LBL_DOMAINS, 8, 0, 1, 1)
        self.LBL_FILENAME = QtWidgets.QLabel(Dialog)
        self.LBL_FILENAME.setObjectName("LBL_FILENAME")
        self.gridLayout.addWidget(self.LBL_FILENAME, 1, 0, 1, 1)
        self.TXT_DOMAINS = QtWidgets.QLineEdit(Dialog)
        self.TXT_DOMAINS.setReadOnly(True)
        self.TXT_DOMAINS.setObjectName("TXT_DOMAINS")
        self.gridLayout.addWidget(self.TXT_DOMAINS, 8, 1, 1, 1)
        self.TXT_FILENAME = QtWidgets.QLineEdit(Dialog)
        self.TXT_FILENAME.setReadOnly(True)
        self.TXT_FILENAME.setObjectName("TXT_FILENAME")
        self.gridLayout.addWidget(self.TXT_FILENAME, 1, 1, 1, 1)
        self.BTN_FILENAME = QtWidgets.QPushButton(Dialog)
        self.BTN_FILENAME.setObjectName("BTN_FILENAME")
        self.gridLayout.addWidget(self.BTN_FILENAME, 1, 2, 1, 1)
        self.BTN_SEQUENCES = QtWidgets.QPushButton(Dialog)
        self.BTN_SEQUENCES.setObjectName("BTN_SEQUENCES")
        self.gridLayout.addWidget(self.BTN_SEQUENCES, 3, 2, 1, 1)
        self.BTN_COMPONENTS = QtWidgets.QPushButton(Dialog)
        self.BTN_COMPONENTS.setObjectName("BTN_COMPONENTS")
        self.gridLayout.addWidget(self.BTN_COMPONENTS, 6, 2, 1, 1)
        self.BTN_DOMAINS = QtWidgets.QPushButton(Dialog)
        self.BTN_DOMAINS.setObjectName("BTN_DOMAINS")
        self.gridLayout.addWidget(self.BTN_DOMAINS, 8, 2, 1, 1)
        self.BTN_ALIGNMENTS = QtWidgets.QPushButton(Dialog)
        self.BTN_ALIGNMENTS.setObjectName("BTN_ALIGNMENTS")
        self.gridLayout.addWidget(self.BTN_ALIGNMENTS, 10, 2, 1, 1)
        self.BTN_TREES = QtWidgets.QPushButton(Dialog)
        self.BTN_TREES.setObjectName("BTN_TREES")
        self.gridLayout.addWidget(self.BTN_TREES, 12, 2, 1, 1)
        self.BTN_FUSIONS = QtWidgets.QPushButton(Dialog)
        self.BTN_FUSIONS.setObjectName("BTN_FUSIONS")
        self.gridLayout.addWidget(self.BTN_FUSIONS, 14, 2, 1, 1)
        self.BTN_NRFG = QtWidgets.QPushButton(Dialog)
        self.BTN_NRFG.setObjectName("BTN_NRFG")
        self.gridLayout.addWidget(self.BTN_NRFG, 16, 2, 1, 1)
        self.LBL_WARN_FILENAME = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_FILENAME.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_FILENAME.setSizePolicy(sizePolicy)
        self.LBL_WARN_FILENAME.setObjectName("LBL_WARN_FILENAME")
        self.gridLayout.addWidget(self.LBL_WARN_FILENAME, 2, 0, 1, 3)
        self.LBL_WARN_SEQUENCES = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_SEQUENCES.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_SEQUENCES.setSizePolicy(sizePolicy)
        self.LBL_WARN_SEQUENCES.setObjectName("LBL_WARN_SEQUENCES")
        self.gridLayout.addWidget(self.LBL_WARN_SEQUENCES, 5, 0, 1, 3)
        self.LBL_WARN_COMPONENTS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_COMPONENTS.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_COMPONENTS.setSizePolicy(sizePolicy)
        self.LBL_WARN_COMPONENTS.setObjectName("LBL_WARN_COMPONENTS")
        self.gridLayout.addWidget(self.LBL_WARN_COMPONENTS, 7, 0, 1, 3)
        self.LBL_WARN_DOMAINS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_DOMAINS.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_DOMAINS.setSizePolicy(sizePolicy)
        self.LBL_WARN_DOMAINS.setObjectName("LBL_WARN_DOMAINS")
        self.gridLayout.addWidget(self.LBL_WARN_DOMAINS, 9, 0, 1, 3)
        self.LBL_WARN_ALIGNMENTS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_ALIGNMENTS.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_ALIGNMENTS.setSizePolicy(sizePolicy)
        self.LBL_WARN_ALIGNMENTS.setObjectName("LBL_WARN_ALIGNMENTS")
        self.gridLayout.addWidget(self.LBL_WARN_ALIGNMENTS, 11, 0, 1, 3)
        self.LBL_WARN_TREES = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_TREES.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_TREES.setSizePolicy(sizePolicy)
        self.LBL_WARN_TREES.setObjectName("LBL_WARN_TREES")
        self.gridLayout.addWidget(self.LBL_WARN_TREES, 13, 0, 1, 3)
        self.LBL_WARN_FUSIONS = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_FUSIONS.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_FUSIONS.setSizePolicy(sizePolicy)
        self.LBL_WARN_FUSIONS.setObjectName("LBL_WARN_FUSIONS")
        self.gridLayout.addWidget(self.LBL_WARN_FUSIONS, 15, 0, 1, 3)
        self.LBL_WARN_NRFG = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_NRFG.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_NRFG.setSizePolicy(sizePolicy)
        self.LBL_WARN_NRFG.setObjectName("LBL_WARN_NRFG")
        self.gridLayout.addWidget(self.LBL_WARN_NRFG, 17, 0, 1, 3)
        self.LBL_WARN_GRAPH = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_WARN_GRAPH.sizePolicy().hasHeightForWidth())
        self.LBL_WARN_GRAPH.setSizePolicy(sizePolicy)
        self.LBL_WARN_GRAPH.setObjectName("LBL_WARN_GRAPH")
        self.gridLayout.addWidget(self.LBL_WARN_GRAPH, 18, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.LBL_NRFG.setText(_translate("Dialog", "NRFG"))
        self.LBL_FUSIONS.setText(_translate("Dialog", "Fusions"))
        self.LBL_ALIGNMENTS.setText(_translate("Dialog", "Alignments"))
        self.LBL_TREES.setText(_translate("Dialog", "Trees"))
        self.LBL_SEQUENCES.setText(_translate("Dialog", "Sequences"))
        self.LBL_COMPONENTS.setText(_translate("Dialog", "Components"))
        self.LBL_DOMAINS.setText(_translate("Dialog", "Domains"))
        self.LBL_FILENAME.setText(_translate("Dialog", "File name"))
        self.BTN_FILENAME.setText(_translate("Dialog", "..."))
        self.BTN_SEQUENCES.setText(_translate("Dialog", "..."))
        self.BTN_COMPONENTS.setText(_translate("Dialog", "..."))
        self.BTN_DOMAINS.setText(_translate("Dialog", "..."))
        self.BTN_ALIGNMENTS.setText(_translate("Dialog", "..."))
        self.BTN_TREES.setText(_translate("Dialog", "..."))
        self.BTN_FUSIONS.setText(_translate("Dialog", "..."))
        self.BTN_NRFG.setText(_translate("Dialog", "..."))
        self.LBL_WARN_FILENAME.setText(_translate("Dialog", "Your model is not saved. You should <a href=\"action:show_save_model\">save</a> your model."))
        self.LBL_WARN_FILENAME.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_SEQUENCES.setText(_translate("Dialog", "You need to <a href=\"action:import_file\">import</a> some data."))
        self.LBL_WARN_SEQUENCES.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_COMPONENTS.setText(_translate("Dialog", "Check your <a href=\"action:show_text_data\">data</a> and generate some <a href=\"action:create_components\">components</a>."))
        self.LBL_WARN_COMPONENTS.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_DOMAINS.setText(_translate("Dialog", "Check your <a href=\"action:show_entities\">components</a> and generate some <a href=\"action:show_domains\">domains</a>."))
        self.LBL_WARN_DOMAINS.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_ALIGNMENTS.setText(_translate("Dialog", "Check your <a href=\"action:show_lego\">domains</a> and generate some <a href=\"action:create_alignments\">alignments</a>."))
        self.LBL_WARN_ALIGNMENTS.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_TREES.setText(_translate("Dialog", "Check your <a href=\"action:show_alignments\">alignments</a> and generate some <a href=\"action:create_trees\">trees</a>."))
        self.LBL_WARN_TREES.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_FUSIONS.setText(_translate("Dialog", "Check your <a href=\"action:show_trees\">trees</a> and genrate some <a href=\"action:create_fusions\">fusions</a>."))
        self.LBL_WARN_FUSIONS.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_NRFG.setText(_translate("Dialog", "Check your <a href=\"action:show_fusions\">fusions</a> and generate the <a href=\"action:create_nrfg\">NRFG</a>."))
        self.LBL_WARN_NRFG.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_WARN_GRAPH.setText(_translate("Dialog", "You\'re all done, take a look at your <a href=\"action:show_trees\">graph</a>."))
        self.LBL_WARN_GRAPH.setProperty("style", _translate("Dialog", "warning"))


