# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_windows_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(201, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_WORKFLOW.sizePolicy().hasHeightForWidth())
        self.BTN_WORKFLOW.setSizePolicy(sizePolicy)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.verticalLayout.addWidget(self.BTN_WORKFLOW)
        self.BTN_WIZARD = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_WIZARD.sizePolicy().hasHeightForWidth())
        self.BTN_WIZARD.setSizePolicy(sizePolicy)
        self.BTN_WIZARD.setObjectName("BTN_WIZARD")
        self.verticalLayout.addWidget(self.BTN_WIZARD)
        self.BTN_ENTITIES = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ENTITIES.sizePolicy().hasHeightForWidth())
        self.BTN_ENTITIES.setSizePolicy(sizePolicy)
        self.BTN_ENTITIES.setObjectName("BTN_ENTITIES")
        self.verticalLayout.addWidget(self.BTN_ENTITIES)
        self.BTN_TEXT = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TEXT.sizePolicy().hasHeightForWidth())
        self.BTN_TEXT.setSizePolicy(sizePolicy)
        self.BTN_TEXT.setObjectName("BTN_TEXT")
        self.verticalLayout.addWidget(self.BTN_TEXT)
        self.BTN_ALIGNMENTS = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ALIGNMENTS.sizePolicy().hasHeightForWidth())
        self.BTN_ALIGNMENTS.setSizePolicy(sizePolicy)
        self.BTN_ALIGNMENTS.setObjectName("BTN_ALIGNMENTS")
        self.verticalLayout.addWidget(self.BTN_ALIGNMENTS)
        self.BTN_FUSIONS = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_FUSIONS.sizePolicy().hasHeightForWidth())
        self.BTN_FUSIONS.setSizePolicy(sizePolicy)
        self.BTN_FUSIONS.setObjectName("BTN_FUSIONS")
        self.verticalLayout.addWidget(self.BTN_FUSIONS)
        self.BTN_LEGO = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_LEGO.sizePolicy().hasHeightForWidth())
        self.BTN_LEGO.setSizePolicy(sizePolicy)
        self.BTN_LEGO.setObjectName("BTN_LEGO")
        self.verticalLayout.addWidget(self.BTN_LEGO)
        self.BTN_LOAD = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_LOAD.sizePolicy().hasHeightForWidth())
        self.BTN_LOAD.setSizePolicy(sizePolicy)
        self.BTN_LOAD.setObjectName("BTN_LOAD")
        self.verticalLayout.addWidget(self.BTN_LOAD)
        self.BTN_LEGOOPTS = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_LEGOOPTS.sizePolicy().hasHeightForWidth())
        self.BTN_LEGOOPTS.setSizePolicy(sizePolicy)
        self.BTN_LEGOOPTS.setObjectName("BTN_LEGOOPTS")
        self.verticalLayout.addWidget(self.BTN_LEGOOPTS)
        self.BTN_TREE = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TREE.sizePolicy().hasHeightForWidth())
        self.BTN_TREE.setSizePolicy(sizePolicy)
        self.BTN_TREE.setObjectName("BTN_TREE")
        self.verticalLayout.addWidget(self.BTN_TREE)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_WIZARD.setText(_translate("Dialog", "Wizard"))
        self.BTN_ENTITIES.setText(_translate("Dialog", "Entities"))
        self.BTN_TEXT.setText(_translate("Dialog", "Text"))
        self.BTN_ALIGNMENTS.setText(_translate("Dialog", "Alignments"))
        self.BTN_FUSIONS.setText(_translate("Dialog", "Fusions"))
        self.BTN_LEGO.setText(_translate("Dialog", "Lego"))
        self.BTN_LOAD.setText(_translate("Dialog", "Load"))
        self.BTN_LEGOOPTS.setText(_translate("Dialog", "Lego options"))
        self.BTN_TREE.setText(_translate("Dialog", "Tree"))

