# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_wizard_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1175, 876)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(128, 100))
        self.label.setMaximumSize(QtCore.QSize(128, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/wizard_logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 3, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 2)
        self.TXT_FILENAME = QtWidgets.QLineEdit(Dialog)
        self.TXT_FILENAME.setObjectName("TXT_FILENAME")
        self.gridLayout.addWidget(self.TXT_FILENAME, 7, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_20 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(140, 0))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.SPN_COMPONENT_TOLERANCE = QtWidgets.QSpinBox(Dialog)
        self.SPN_COMPONENT_TOLERANCE.setMinimumSize(QtCore.QSize(128, 0))
        self.SPN_COMPONENT_TOLERANCE.setObjectName("SPN_COMPONENT_TOLERANCE")
        self.horizontalLayout_4.addWidget(self.SPN_COMPONENT_TOLERANCE)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.label_21 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(140, 0))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.CMB_ALIGNMENT_METHOD = QtWidgets.QComboBox(Dialog)
        self.CMB_ALIGNMENT_METHOD.setMinimumSize(QtCore.QSize(128, 0))
        self.CMB_ALIGNMENT_METHOD.setObjectName("CMB_ALIGNMENT_METHOD")
        self.horizontalLayout_4.addWidget(self.CMB_ALIGNMENT_METHOD)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_22 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(140, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.CMB_TREE_METHOD = QtWidgets.QComboBox(Dialog)
        self.CMB_TREE_METHOD.setMinimumSize(QtCore.QSize(128, 0))
        self.CMB_TREE_METHOD.setObjectName("CMB_TREE_METHOD")
        self.horizontalLayout_4.addWidget(self.CMB_TREE_METHOD)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(140, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.CHK_PAUSE_DATA = QtWidgets.QCheckBox(Dialog)
        self.CHK_PAUSE_DATA.setMinimumSize(QtCore.QSize(128, 0))
        self.CHK_PAUSE_DATA.setObjectName("CHK_PAUSE_DATA")
        self.horizontalLayout_3.addWidget(self.CHK_PAUSE_DATA)
        self.CHK_PAUSE_COMPONENTS = QtWidgets.QCheckBox(Dialog)
        self.CHK_PAUSE_COMPONENTS.setMinimumSize(QtCore.QSize(128, 0))
        self.CHK_PAUSE_COMPONENTS.setObjectName("CHK_PAUSE_COMPONENTS")
        self.horizontalLayout_3.addWidget(self.CHK_PAUSE_COMPONENTS)
        self.CHK_PAUSE_ALIGNMENTS = QtWidgets.QCheckBox(Dialog)
        self.CHK_PAUSE_ALIGNMENTS.setMinimumSize(QtCore.QSize(128, 0))
        self.CHK_PAUSE_ALIGNMENTS.setObjectName("CHK_PAUSE_ALIGNMENTS")
        self.horizontalLayout_3.addWidget(self.CHK_PAUSE_ALIGNMENTS)
        self.CHK_PAUSE_TREES = QtWidgets.QCheckBox(Dialog)
        self.CHK_PAUSE_TREES.setMinimumSize(QtCore.QSize(128, 0))
        self.CHK_PAUSE_TREES.setObjectName("CHK_PAUSE_TREES")
        self.horizontalLayout_3.addWidget(self.CHK_PAUSE_TREES)
        self.CHK_PAUSE_FUSIONS = QtWidgets.QCheckBox(Dialog)
        self.CHK_PAUSE_FUSIONS.setMinimumSize(QtCore.QSize(128, 0))
        self.CHK_PAUSE_FUSIONS.setObjectName("CHK_PAUSE_FUSIONS")
        self.horizontalLayout_3.addWidget(self.CHK_PAUSE_FUSIONS)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 13, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.BTN_REMOVE_FILE = QtWidgets.QPushButton(Dialog)
        self.BTN_REMOVE_FILE.setObjectName("BTN_REMOVE_FILE")
        self.gridLayout_3.addWidget(self.BTN_REMOVE_FILE, 1, 1, 1, 1)
        self.BTN_ADD_FILE = QtWidgets.QPushButton(Dialog)
        self.BTN_ADD_FILE.setObjectName("BTN_ADD_FILE")
        self.gridLayout_3.addWidget(self.BTN_ADD_FILE, 0, 1, 1, 1)
        self.BTN_SAMPLES = QtWidgets.QPushButton(Dialog)
        self.BTN_SAMPLES.setObjectName("BTN_SAMPLES")
        self.gridLayout_3.addWidget(self.BTN_SAMPLES, 3, 1, 1, 1)
        self.LST_FILES = QtWidgets.QTreeWidget(Dialog)
        self.LST_FILES.setObjectName("LST_FILES")
        self.LST_FILES.headerItem().setText(0, "1")
        self.LST_FILES.header().setVisible(False)
        self.gridLayout_3.addWidget(self.LST_FILES, 0, 0, 4, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 10, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.BTN_OK = QtWidgets.QPushButton(Dialog)
        self.BTN_OK.setObjectName("BTN_OK")
        self.horizontalLayout.addWidget(self.BTN_OK)
        self.gridLayout.addLayout(self.horizontalLayout, 15, 0, 1, 2)
        self.LBL_HELP_TITLE = QtWidgets.QLabel(Dialog)
        self.LBL_HELP_TITLE.setObjectName("LBL_HELP_TITLE")
        self.gridLayout.addWidget(self.LBL_HELP_TITLE, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 14, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 11, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.BTN_RECENT = QtWidgets.QPushButton(Dialog)
        self.BTN_RECENT.setObjectName("BTN_RECENT")
        self.horizontalLayout_2.addWidget(self.BTN_RECENT)
        self.BTN_SAVE = QtWidgets.QPushButton(Dialog)
        self.BTN_SAVE.setObjectName("BTN_SAVE")
        self.horizontalLayout_2.addWidget(self.BTN_SAVE)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "Give your session a name."))
        self.label_10.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_7.setText(_translate("Dialog", "Name"))
        self.label_7.setProperty("style", _translate("Dialog", "heading"))
        self.label_13.setText(_translate("Dialog", "Choose your tools."))
        self.label_13.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_11.setText(_translate("Dialog", "Specify at least one FASTA file and a corresponding BLAST file."))
        self.label_11.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_20.setText(_translate("Dialog", "Component tolerance"))
        self.label_21.setText(_translate("Dialog", "Alignment method"))
        self.label_22.setText(_translate("Dialog", "Tree method"))
        self.label_23.setText(_translate("Dialog", "Pause to review"))
        self.CHK_PAUSE_DATA.setText(_translate("Dialog", "Data"))
        self.CHK_PAUSE_COMPONENTS.setText(_translate("Dialog", "Components"))
        self.CHK_PAUSE_ALIGNMENTS.setText(_translate("Dialog", "Alignments"))
        self.CHK_PAUSE_TREES.setText(_translate("Dialog", "Trees"))
        self.CHK_PAUSE_FUSIONS.setText(_translate("Dialog", "Fusions"))
        self.BTN_REMOVE_FILE.setText(_translate("Dialog", "Remove"))
        self.BTN_ADD_FILE.setText(_translate("Dialog", "Add"))
        self.BTN_SAMPLES.setText(_translate("Dialog", "Sample"))
        self.BTN_SAMPLES.setProperty("style", _translate("Dialog", "dropdown"))
        self.label_14.setText(_translate("Dialog", "When you\'re ready, click review to continue..."))
        self.label_14.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_OK.setText(_translate("Dialog", "Review"))
        self.LBL_HELP_TITLE.setText(_translate("Dialog", "The wizard performs the complete Groot workflow at once. If you\'d like to play by yourself, consider using the <a href=\"action:show_workflow\">workflow</a> instead."))
        self.LBL_HELP_TITLE.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_8.setText(_translate("Dialog", "Data"))
        self.label_8.setProperty("style", _translate("Dialog", "heading"))
        self.label_15.setText(_translate("Dialog", "History"))
        self.label_15.setProperty("style", _translate("Dialog", "heading"))
        self.label_24.setText(_translate("Dialog", "Power on"))
        self.label_24.setProperty("style", _translate("Dialog", "heading"))
        self.label_9.setText(_translate("Dialog", "Groot Wizard"))
        self.label_9.setProperty("style", _translate("Dialog", "title"))
        self.label_19.setText(_translate("Dialog", "Methods and parameters"))
        self.label_19.setProperty("style", _translate("Dialog", "heading"))
        self.label_12.setText(_translate("Dialog", "Already have a set of preferred settings? Select them here."))
        self.label_12.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_RECENT.setText(_translate("Dialog", "Load"))
        self.BTN_RECENT.setProperty("style", _translate("Dialog", "dropdown"))
        self.BTN_SAVE.setText(_translate("Dialog", "Save"))


