# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_view_options_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(837, 872)
        Dialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalFrame_8 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RAD_MODE_COMPONENT = QtWidgets.QRadioButton(self.horizontalFrame_8)
        self.RAD_MODE_COMPONENT.setObjectName("RAD_MODE_COMPONENT")
        self.horizontalLayout_3.addWidget(self.RAD_MODE_COMPONENT)
        self.RAD_MODE_GENE = QtWidgets.QRadioButton(self.horizontalFrame_8)
        self.RAD_MODE_GENE.setObjectName("RAD_MODE_GENE")
        self.horizontalLayout_3.addWidget(self.RAD_MODE_GENE)
        self.RAD_MODE_DOMAIN = QtWidgets.QRadioButton(self.horizontalFrame_8)
        self.RAD_MODE_DOMAIN.setObjectName("RAD_MODE_DOMAIN")
        self.horizontalLayout_3.addWidget(self.RAD_MODE_DOMAIN)
        self.RAD_MODE_EDGE = QtWidgets.QRadioButton(self.horizontalFrame_8)
        self.RAD_MODE_EDGE.setObjectName("RAD_MODE_EDGE")
        self.horizontalLayout_3.addWidget(self.RAD_MODE_EDGE)
        self.verticalLayout.addWidget(self.horizontalFrame_8)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalFrame = QtWidgets.QFrame(Dialog)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAD_NAME_YES = QtWidgets.QRadioButton(self.horizontalFrame)
        self.RAD_NAME_YES.setObjectName("RAD_NAME_YES")
        self.horizontalLayout.addWidget(self.RAD_NAME_YES)
        self.RAD_NAME_NO = QtWidgets.QRadioButton(self.horizontalFrame)
        self.RAD_NAME_NO.setObjectName("RAD_NAME_NO")
        self.horizontalLayout.addWidget(self.RAD_NAME_NO)
        self.RAD_NAME_IND = QtWidgets.QRadioButton(self.horizontalFrame)
        self.RAD_NAME_IND.setObjectName("RAD_NAME_IND")
        self.horizontalLayout.addWidget(self.RAD_NAME_IND)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalFrame_2 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAD_PIANO_YES = QtWidgets.QRadioButton(self.horizontalFrame_2)
        self.RAD_PIANO_YES.setObjectName("RAD_PIANO_YES")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_YES)
        self.RAD_PIANO_NO = QtWidgets.QRadioButton(self.horizontalFrame_2)
        self.RAD_PIANO_NO.setObjectName("RAD_PIANO_NO")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_NO)
        self.RAD_PIANO_IND = QtWidgets.QRadioButton(self.horizontalFrame_2)
        self.RAD_PIANO_IND.setObjectName("RAD_PIANO_IND")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalFrame_4 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RAD_POS_YES = QtWidgets.QRadioButton(self.horizontalFrame_4)
        self.RAD_POS_YES.setObjectName("RAD_POS_YES")
        self.horizontalLayout_5.addWidget(self.RAD_POS_YES)
        self.RAD_POS_NO = QtWidgets.QRadioButton(self.horizontalFrame_4)
        self.RAD_POS_NO.setObjectName("RAD_POS_NO")
        self.horizontalLayout_5.addWidget(self.RAD_POS_NO)
        self.RAD_POS_IND = QtWidgets.QRadioButton(self.horizontalFrame_4)
        self.RAD_POS_IND.setObjectName("RAD_POS_IND")
        self.horizontalLayout_5.addWidget(self.RAD_POS_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_4)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalFrame_9 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RAD_COMPONENTS_YES = QtWidgets.QRadioButton(self.horizontalFrame_9)
        self.RAD_COMPONENTS_YES.setObjectName("RAD_COMPONENTS_YES")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_YES)
        self.RAD_COMPONENTS_NO = QtWidgets.QRadioButton(self.horizontalFrame_9)
        self.RAD_COMPONENTS_NO.setObjectName("RAD_COMPONENTS_NO")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_NO)
        self.RAD_COMPONENTS_IND = QtWidgets.QRadioButton(self.horizontalFrame_9)
        self.RAD_COMPONENTS_IND.setObjectName("RAD_COMPONENTS_IND")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_9)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalFrame_3 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RAD_MOVE_YES = QtWidgets.QRadioButton(self.horizontalFrame_3)
        self.RAD_MOVE_YES.setObjectName("RAD_MOVE_YES")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_YES)
        self.RAD_MOVE_NO = QtWidgets.QRadioButton(self.horizontalFrame_3)
        self.RAD_MOVE_NO.setObjectName("RAD_MOVE_NO")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_NO)
        self.RAD_MOVE_IND = QtWidgets.QRadioButton(self.horizontalFrame_3)
        self.RAD_MOVE_IND.setObjectName("RAD_MOVE_IND")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_3)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalFrame_5 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RAD_XSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_5)
        self.RAD_XSNAP_YES.setObjectName("RAD_XSNAP_YES")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_YES)
        self.RAD_XSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_5)
        self.RAD_XSNAP_NO.setObjectName("RAD_XSNAP_NO")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_NO)
        self.RAD_XSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_5)
        self.RAD_XSNAP_IND.setObjectName("RAD_XSNAP_IND")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_5)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalFrame_6 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RAD_YSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_6)
        self.RAD_YSNAP_YES.setObjectName("RAD_YSNAP_YES")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_YES)
        self.RAD_YSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_6)
        self.RAD_YSNAP_NO.setObjectName("RAD_YSNAP_NO")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_NO)
        self.RAD_YSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_6)
        self.RAD_YSNAP_IND.setObjectName("RAD_YSNAP_IND")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_IND)
        self.verticalLayout.addWidget(self.horizontalFrame_6)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalFrame_7 = QtWidgets.QFrame(Dialog)
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalFrame_7)
        self.gridLayout.setObjectName("gridLayout")
        self.RAD_DOMAIN_FIXEDNUMBER = QtWidgets.QRadioButton(self.horizontalFrame_7)
        self.RAD_DOMAIN_FIXEDNUMBER.setObjectName("RAD_DOMAIN_FIXEDNUMBER")
        self.gridLayout.addWidget(self.RAD_DOMAIN_FIXEDNUMBER, 0, 2, 1, 1)
        self.RAD_DOMAIN_COMPONENT = QtWidgets.QRadioButton(self.horizontalFrame_7)
        self.RAD_DOMAIN_COMPONENT.setObjectName("RAD_DOMAIN_COMPONENT")
        self.gridLayout.addWidget(self.RAD_DOMAIN_COMPONENT, 0, 0, 1, 1)
        self.RAD_DOMAIN_FIXEDWIDTH = QtWidgets.QRadioButton(self.horizontalFrame_7)
        self.RAD_DOMAIN_FIXEDWIDTH.setObjectName("RAD_DOMAIN_FIXEDWIDTH")
        self.gridLayout.addWidget(self.RAD_DOMAIN_FIXEDWIDTH, 0, 1, 1, 1)
        self.SPN_DOMAIN_PARAMETER = QtWidgets.QSpinBox(self.horizontalFrame_7)
        self.SPN_DOMAIN_PARAMETER.setMinimum(1)
        self.SPN_DOMAIN_PARAMETER.setMaximum(1000)
        self.SPN_DOMAIN_PARAMETER.setObjectName("SPN_DOMAIN_PARAMETER")
        self.gridLayout.addWidget(self.SPN_DOMAIN_PARAMETER, 1, 1, 1, 2)
        self.LBL_DOMAIN_PARAMETER = QtWidgets.QLabel(self.horizontalFrame_7)
        self.LBL_DOMAIN_PARAMETER.setObjectName("LBL_DOMAIN_PARAMETER")
        self.gridLayout.addWidget(self.LBL_DOMAIN_PARAMETER, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.horizontalFrame_7)
        spacerItem = QtWidgets.QSpacerItem(141, 241, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "View"))
        self.label_4.setProperty("style", _translate("Dialog", "heading"))
        self.label_9.setText(_translate("Dialog", "Mode"))
        self.label_9.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_MODE_COMPONENT.setText(_translate("Dialog", "Component"))
        self.RAD_MODE_GENE.setText(_translate("Dialog", "Gene"))
        self.RAD_MODE_DOMAIN.setText(_translate("Dialog", "Domain"))
        self.RAD_MODE_EDGE.setText(_translate("Dialog", "Edge"))
        self.label.setText(_translate("Dialog", "Names"))
        self.label.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_NAME_YES.setText(_translate("Dialog", "Always"))
        self.RAD_NAME_NO.setText(_translate("Dialog", "Never"))
        self.RAD_NAME_IND.setText(_translate("Dialog", "When selected"))
        self.label_2.setText(_translate("Dialog", "Piano rolls"))
        self.label_2.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_PIANO_YES.setText(_translate("Dialog", "Always"))
        self.RAD_PIANO_NO.setText(_translate("Dialog", "Never"))
        self.RAD_PIANO_IND.setText(_translate("Dialog", "When selected"))
        self.label_5.setText(_translate("Dialog", "Positions"))
        self.label_5.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_POS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_POS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_POS_IND.setText(_translate("Dialog", "When selected"))
        self.label_10.setText(_translate("Dialog", "Components"))
        self.label_10.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_COMPONENTS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_COMPONENTS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_COMPONENTS_IND.setText(_translate("Dialog", "When selected"))
        self.label_3.setText(_translate("Dialog", "Movement"))
        self.label_3.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_MOVE_YES.setText(_translate("Dialog", "Always"))
        self.RAD_MOVE_NO.setText(_translate("Dialog", "Never"))
        self.RAD_MOVE_IND.setText(_translate("Dialog", "Double click toggles"))
        self.label_6.setText(_translate("Dialog", "X-snap"))
        self.label_6.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_XSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_XSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_XSNAP_IND.setText(_translate("Dialog", "Without ᴄᴛʀʟ"))
        self.label_7.setText(_translate("Dialog", "Y-snap"))
        self.label_7.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_YSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_YSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_YSNAP_IND.setText(_translate("Dialog", "Without ᴀʟᴛ"))
        self.label_8.setText(_translate("Dialog", "Domain generator"))
        self.label_8.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_DOMAIN_FIXEDNUMBER.setText(_translate("Dialog", "Fixed number"))
        self.RAD_DOMAIN_COMPONENT.setText(_translate("Dialog", "Component"))
        self.RAD_DOMAIN_FIXEDWIDTH.setText(_translate("Dialog", "Fixed-width"))
        self.LBL_DOMAIN_PARAMETER.setText(_translate("Dialog", "Parameter:"))


