# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_view_options_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(817, 795)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.BTN_CLEAR_RECENT = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_CLEAR_RECENT.sizePolicy().hasHeightForWidth())
        self.BTN_CLEAR_RECENT.setSizePolicy(sizePolicy)
        self.BTN_CLEAR_RECENT.setObjectName("BTN_CLEAR_RECENT")
        self.verticalLayout_3.addWidget(self.BTN_CLEAR_RECENT)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.LBL_VISJS_WARNING = QtWidgets.QLabel(self.tab)
        self.LBL_VISJS_WARNING.setObjectName("LBL_VISJS_WARNING")
        self.verticalLayout_3.addWidget(self.LBL_VISJS_WARNING)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TXT_VISJS = QtWidgets.QLineEdit(self.tab)
        self.TXT_VISJS.setObjectName("TXT_VISJS")
        self.horizontalLayout_3.addWidget(self.TXT_VISJS)
        self.BTN_VISJS = QtWidgets.QPushButton(self.tab)
        self.BTN_VISJS.setObjectName("BTN_VISJS")
        self.horizontalLayout_3.addWidget(self.BTN_VISJS)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RAD_TREE_ASK = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_ASK.setObjectName("RAD_TREE_ASK")
        self.verticalLayout_4.addWidget(self.RAD_TREE_ASK)
        self.RAD_TREE_SYSTEM = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_SYSTEM.setObjectName("RAD_TREE_SYSTEM")
        self.verticalLayout_4.addWidget(self.RAD_TREE_SYSTEM)
        self.RAD_TREE_INBUILT = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_INBUILT.setObjectName("RAD_TREE_INBUILT")
        self.verticalLayout_4.addWidget(self.RAD_TREE_INBUILT)
        self.verticalLayout_3.addWidget(self.frame)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RAD_STARTUP_MESSAGE = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_MESSAGE.setObjectName("RAD_STARTUP_MESSAGE")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_MESSAGE)
        self.RAD_STARTUP_WORKFLOW = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_WORKFLOW.setObjectName("RAD_STARTUP_WORKFLOW")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_WORKFLOW)
        self.RAD_STARTUP_SAMPLES = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_SAMPLES.setObjectName("RAD_STARTUP_SAMPLES")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_SAMPLES)
        self.RAD_STARTUP_NOTHING = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_NOTHING.setObjectName("RAD_STARTUP_NOTHING")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_NOTHING)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 303, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.RAD_THEME_DEFAULT = QtWidgets.QRadioButton(self.tab_3)
        self.RAD_THEME_DEFAULT.setObjectName("RAD_THEME_DEFAULT")
        self.verticalLayout_6.addWidget(self.RAD_THEME_DEFAULT)
        self.RAD_THEME_SYSTEM = QtWidgets.QRadioButton(self.tab_3)
        self.RAD_THEME_SYSTEM.setObjectName("RAD_THEME_SYSTEM")
        self.verticalLayout_6.addWidget(self.RAD_THEME_SYSTEM)
        self.RAD_THEME_INTERMAKE = QtWidgets.QRadioButton(self.tab_3)
        self.RAD_THEME_INTERMAKE.setObjectName("RAD_THEME_INTERMAKE")
        self.verticalLayout_6.addWidget(self.RAD_THEME_INTERMAKE)
        self.RAD_THEME_CUSTOM = QtWidgets.QRadioButton(self.tab_3)
        self.RAD_THEME_CUSTOM.setObjectName("RAD_THEME_CUSTOM")
        self.verticalLayout_6.addWidget(self.RAD_THEME_CUSTOM)
        self.FRA_THEME_CUSTOM = QtWidgets.QFrame(self.tab_3)
        self.FRA_THEME_CUSTOM.setFrameShape(QtWidgets.QFrame.Panel)
        self.FRA_THEME_CUSTOM.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FRA_THEME_CUSTOM.setObjectName("FRA_THEME_CUSTOM")
        self.gridLayout = QtWidgets.QGridLayout(self.FRA_THEME_CUSTOM)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.FRA_THEME_CUSTOM)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.CMB_THEME = QtWidgets.QComboBox(self.FRA_THEME_CUSTOM)
        self.CMB_THEME.setObjectName("CMB_THEME")
        self.gridLayout.addWidget(self.CMB_THEME, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.FRA_THEME_CUSTOM)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.TXT_CSS = QtWidgets.QLineEdit(self.FRA_THEME_CUSTOM)
        self.TXT_CSS.setObjectName("TXT_CSS")
        self.gridLayout.addWidget(self.TXT_CSS, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.FRA_THEME_CUSTOM)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.BTN_INTERMAKE_ADVANCED = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_INTERMAKE_ADVANCED.sizePolicy().hasHeightForWidth())
        self.BTN_INTERMAKE_ADVANCED.setSizePolicy(sizePolicy)
        self.BTN_INTERMAKE_ADVANCED.setObjectName("BTN_INTERMAKE_ADVANCED")
        self.verticalLayout_6.addWidget(self.BTN_INTERMAKE_ADVANCED)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalFrame = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAD_NAME_YES = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_YES.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_YES.setSizePolicy(sizePolicy)
        self.RAD_NAME_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_YES.setObjectName("RAD_NAME_YES")
        self.horizontalLayout.addWidget(self.RAD_NAME_YES)
        self.RAD_NAME_NO = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_NO.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_NO.setSizePolicy(sizePolicy)
        self.RAD_NAME_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_NO.setObjectName("RAD_NAME_NO")
        self.horizontalLayout.addWidget(self.RAD_NAME_NO)
        self.RAD_NAME_IND = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_IND.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_IND.setSizePolicy(sizePolicy)
        self.RAD_NAME_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_IND.setObjectName("RAD_NAME_IND")
        self.horizontalLayout.addWidget(self.RAD_NAME_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAD_PIANO_YES = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_YES.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_YES.setSizePolicy(sizePolicy)
        self.RAD_PIANO_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_YES.setObjectName("RAD_PIANO_YES")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_YES)
        self.RAD_PIANO_NO = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_NO.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_NO.setSizePolicy(sizePolicy)
        self.RAD_PIANO_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_NO.setObjectName("RAD_PIANO_NO")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_NO)
        self.RAD_PIANO_IND = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_IND.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_IND.setSizePolicy(sizePolicy)
        self.RAD_PIANO_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_IND.setObjectName("RAD_PIANO_IND")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_2)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RAD_POS_YES = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_POS_YES.setSizePolicy(sizePolicy)
        self.RAD_POS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_YES.setObjectName("RAD_POS_YES")
        self.horizontalLayout_5.addWidget(self.RAD_POS_YES)
        self.RAD_POS_NO = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_POS_NO.setSizePolicy(sizePolicy)
        self.RAD_POS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_NO.setObjectName("RAD_POS_NO")
        self.horizontalLayout_5.addWidget(self.RAD_POS_NO)
        self.RAD_POS_IND = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_POS_IND.setSizePolicy(sizePolicy)
        self.RAD_POS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_IND.setObjectName("RAD_POS_IND")
        self.horizontalLayout_5.addWidget(self.RAD_POS_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_4)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalFrame_9 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RAD_COMPONENTS_YES = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_YES.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_YES.setObjectName("RAD_COMPONENTS_YES")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_YES)
        self.RAD_COMPONENTS_NO = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_NO.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_NO.setObjectName("RAD_COMPONENTS_NO")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_NO)
        self.RAD_COMPONENTS_IND = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_IND.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_IND.setObjectName("RAD_COMPONENTS_IND")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_9)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RAD_MOVE_YES = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_YES.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_YES.setSizePolicy(sizePolicy)
        self.RAD_MOVE_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_YES.setObjectName("RAD_MOVE_YES")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_YES)
        self.RAD_MOVE_NO = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_NO.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_NO.setSizePolicy(sizePolicy)
        self.RAD_MOVE_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_NO.setObjectName("RAD_MOVE_NO")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_NO)
        self.RAD_MOVE_IND = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_IND.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_IND.setSizePolicy(sizePolicy)
        self.RAD_MOVE_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_IND.setObjectName("RAD_MOVE_IND")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_3)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalFrame_5 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RAD_XSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_YES.setObjectName("RAD_XSNAP_YES")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_YES)
        self.RAD_XSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_NO.setObjectName("RAD_XSNAP_NO")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_NO)
        self.RAD_XSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_IND.setObjectName("RAD_XSNAP_IND")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_5)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.tab_2)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RAD_YSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_YES.setObjectName("RAD_YSNAP_YES")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_YES)
        self.RAD_YSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_NO.setObjectName("RAD_YSNAP_NO")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_NO)
        self.RAD_YSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_IND.setObjectName("RAD_YSNAP_IND")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_IND)
        self.verticalLayout_2.addWidget(self.horizontalFrame_6)
        spacerItem2 = QtWidgets.QSpacerItem(141, 241, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_16.setText(_translate("Dialog", "These settings affect all Groot sessions."))
        self.label_16.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_4.setText(_translate("Dialog", "Recent files history"))
        self.label_4.setProperty("style", _translate("Dialog", "subheading"))
        self.BTN_CLEAR_RECENT.setText(_translate("Dialog", "Clear"))
        self.label_8.setText(_translate("Dialog", "vis.js"))
        self.label_8.setProperty("style", _translate("Dialog", "subheading"))
        self.LBL_VISJS_WARNING.setText(_translate("Dialog", "You must configure the vis.js path in order to use the tree browser. Point this at the directory containing the \'visjs\' folder."))
        self.LBL_VISJS_WARNING.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_VISJS.setText(_translate("Dialog", "Browse"))
        self.label_11.setText(_translate("Dialog", "Graph browser"))
        self.label_11.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_TREE_ASK.setText(_translate("Dialog", "Ask every time"))
        self.RAD_TREE_SYSTEM.setText(_translate("Dialog", "Only use the system browser"))
        self.RAD_TREE_INBUILT.setText(_translate("Dialog", "Only use the inbult browser"))
        self.label_9.setText(_translate("Dialog", "Startup"))
        self.label_9.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_STARTUP_MESSAGE.setText(_translate("Dialog", "Show the startup message"))
        self.RAD_STARTUP_WORKFLOW.setText(_translate("Dialog", "Show the workflow"))
        self.RAD_STARTUP_SAMPLES.setText(_translate("Dialog", "Show the samples browser"))
        self.RAD_STARTUP_NOTHING.setText(_translate("Dialog", "Don\'t show anything"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Groot"))
        self.label_18.setText(_translate("Dialog", "Conifigure how Intermake should handle Groot."))
        self.label_18.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_12.setText(_translate("Dialog", "Theme"))
        self.label_12.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_THEME_DEFAULT.setText(_translate("Dialog", "Default"))
        self.RAD_THEME_SYSTEM.setText(_translate("Dialog", "System"))
        self.RAD_THEME_INTERMAKE.setText(_translate("Dialog", "Intermake"))
        self.RAD_THEME_CUSTOM.setText(_translate("Dialog", "Custom"))
        self.label_14.setText(_translate("Dialog", "Theme"))
        self.label_15.setText(_translate("Dialog", "CSS"))
        self.label_13.setText(_translate("Dialog", "Advanced"))
        self.label_13.setProperty("style", _translate("Dialog", "subheading"))
        self.BTN_INTERMAKE_ADVANCED.setText(_translate("Dialog", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Intermake"))
        self.label_19.setText(_translate("Dialog", "These settings only affect the current model."))
        self.label_19.setProperty("style", _translate("Dialog", "helpbox"))
        self.label.setText(_translate("Dialog", "Gene names"))
        self.label.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_NAME_YES.setText(_translate("Dialog", "Always"))
        self.RAD_NAME_NO.setText(_translate("Dialog", "Never"))
        self.RAD_NAME_IND.setText(_translate("Dialog", "When selected"))
        self.label_2.setText(_translate("Dialog", "Piano rolls"))
        self.label_2.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_PIANO_YES.setText(_translate("Dialog", "Always"))
        self.RAD_PIANO_NO.setText(_translate("Dialog", "Never"))
        self.RAD_PIANO_IND.setText(_translate("Dialog", "When selected"))
        self.label_5.setText(_translate("Dialog", "Positions"))
        self.label_5.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_POS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_POS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_POS_IND.setText(_translate("Dialog", "When selected"))
        self.label_10.setText(_translate("Dialog", "Components"))
        self.label_10.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_COMPONENTS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_COMPONENTS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_COMPONENTS_IND.setText(_translate("Dialog", "When selected"))
        self.label_3.setText(_translate("Dialog", "Movement"))
        self.label_3.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_MOVE_YES.setText(_translate("Dialog", "Always"))
        self.RAD_MOVE_NO.setText(_translate("Dialog", "Never"))
        self.RAD_MOVE_IND.setText(_translate("Dialog", "Double click toggles"))
        self.label_6.setText(_translate("Dialog", "X-snap"))
        self.label_6.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_XSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_XSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_XSNAP_IND.setText(_translate("Dialog", "Without ᴄᴛʀʟ"))
        self.label_7.setText(_translate("Dialog", "Y-snap"))
        self.label_7.setProperty("style", _translate("Dialog", "subheading"))
        self.RAD_YSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_YSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_YSNAP_IND.setText(_translate("Dialog", "Without ᴀʟᴛ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Lego"))


