# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_main_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 796)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MDI_AREA = QtWidgets.QMdiArea(self.centralwidget)
        self.MDI_AREA.setObjectName("MDI_AREA")
        self.gridLayout.addWidget(self.MDI_AREA, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1101, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_Windows = QtWidgets.QMenu(self.menuBar)
        self.menu_Windows.setObjectName("menu_Windows")
        MainWindow.setMenuBar(self.menuBar)
        self.ACT_WORKFLOW = QtWidgets.QAction(MainWindow)
        self.ACT_WORKFLOW.setObjectName("ACT_WORKFLOW")
        self.ACT_WIZARD = QtWidgets.QAction(MainWindow)
        self.ACT_WIZARD.setObjectName("ACT_WIZARD")
        self.ACT_LEGO = QtWidgets.QAction(MainWindow)
        self.ACT_LEGO.setObjectName("ACT_LEGO")
        self.ACT_TREE = QtWidgets.QAction(MainWindow)
        self.ACT_TREE.setObjectName("ACT_TREE")
        self.ACT_TEXT = QtWidgets.QAction(MainWindow)
        self.ACT_TEXT.setObjectName("ACT_TEXT")
        self.ACT_ENTITIES = QtWidgets.QAction(MainWindow)
        self.ACT_ENTITIES.setObjectName("ACT_ENTITIES")
        self.ACT_ALIGNMENTS = QtWidgets.QAction(MainWindow)
        self.ACT_ALIGNMENTS.setObjectName("ACT_ALIGNMENTS")
        self.ACT_FUSION = QtWidgets.QAction(MainWindow)
        self.ACT_FUSION.setObjectName("ACT_FUSION")
        self.ACT_SAMPLES = QtWidgets.QAction(MainWindow)
        self.ACT_SAMPLES.setObjectName("ACT_SAMPLES")
        self.ACT_INTERMAKE = QtWidgets.QAction(MainWindow)
        self.ACT_INTERMAKE.setObjectName("ACT_INTERMAKE")
        self.ACT_DOMAIN = QtWidgets.QAction(MainWindow)
        self.ACT_DOMAIN.setObjectName("ACT_DOMAIN")
        self.ACT_DEBUG = QtWidgets.QAction(MainWindow)
        self.ACT_DEBUG.setObjectName("ACT_DEBUG")
        self.menu_Windows.addAction(self.ACT_SAMPLES)
        self.menu_Windows.addAction(self.ACT_WORKFLOW)
        self.menu_Windows.addAction(self.ACT_WIZARD)
        self.menu_Windows.addAction(self.ACT_LEGO)
        self.menu_Windows.addAction(self.ACT_TREE)
        self.menu_Windows.addAction(self.ACT_TEXT)
        self.menu_Windows.addAction(self.ACT_ENTITIES)
        self.menu_Windows.addAction(self.ACT_ALIGNMENTS)
        self.menu_Windows.addAction(self.ACT_FUSION)
        self.menu_Windows.addAction(self.ACT_INTERMAKE)
        self.menu_Windows.addAction(self.ACT_DOMAIN)
        self.menu_Windows.addAction(self.ACT_DEBUG)
        self.menuBar.addAction(self.menu_Windows.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_Windows.setTitle(_translate("MainWindow", "&Windows"))
        self.ACT_WORKFLOW.setText(_translate("MainWindow", "&Workflow"))
        self.ACT_WIZARD.setText(_translate("MainWindow", "&Wizard"))
        self.ACT_LEGO.setText(_translate("MainWindow", "&Lego diagram"))
        self.ACT_TREE.setText(_translate("MainWindow", "&Tree diagram"))
        self.ACT_TEXT.setText(_translate("MainWindow", "&Textual data"))
        self.ACT_ENTITIES.setText(_translate("MainWindow", "&Model entities"))
        self.ACT_ALIGNMENTS.setText(_translate("MainWindow", "&Alignment viewer"))
        self.ACT_FUSION.setText(_translate("MainWindow", "&Fusion viewer"))
        self.ACT_SAMPLES.setText(_translate("MainWindow", "&Examples"))
        self.ACT_INTERMAKE.setText(_translate("MainWindow", "&Intermake"))
        self.ACT_DOMAIN.setText(_translate("MainWindow", "&Domain generator"))
        self.ACT_DEBUG.setText(_translate("MainWindow", "De&bug"))

